dataset:
  data_file_path: ../data/ParaNMT50m_original/_after_tree_train_data_multitask.h5
  index_file_path: ../data/ParaNMT50m_original/train_data_multitask_medium_with_full_scpg_index_random.h5
  max_length: 300
  padding_strategy: longest
use_cached_data: false
force_recache: false
val_data_dir: ../data/ParaNMT50m_original/val_data
evaluator:
  evalb_executable_path: ../evaluation/apps/EVALB/evalb
  evalb_param_file_path: ../evaluation/apps/EVALB/sample/sample.prm
  tree_format: bracket
seed: 114514
model_name_or_path: ../pretrained-models/syntax-t5-base-node-with-NT/
tokenizer_name_or_path: ../pretrained-models/syntax-t5-base-node-with-NT/
batch_size: 32
val_batch_size: 64
num_epochs: 1
prefetch_factor: 2
lr: 5.0e-05
gradient_accumulation_steps: 16
num_warmup_steps: 1000
output_dir: ./runs/after_1_10_tree_bracket_1_6
checkpoint_every: 512
evaluate_every: 8192
resume: false
evaluation_only: false
logging:
  format: '%(asctime)s %(levelname)s %(filename)s:%(lineno)d -- %(message)s'
  level: 20
